# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  GO111MODULE: 'on'

steps:
  - bash: GOBIN=$PWD/bin go install ./...
    displayName: 'Get dependencies, then build'

  - bash: go test
    displayName: 'Test'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/lambda-twitter'
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-twitter.zip'
    displayName: 'Zip Lambda (twitter)'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/lambda-mastodon'
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-mastodon.zip'
    displayName: 'Zip Lambda (Mastodon)'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'buyout-bot-zip'
      targetPath: '$(Build.ArtifactStagingDirectory)'
