# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  GO111MODULE: 'on'
  System.Debug: 'true'

steps:
- script: |
    go build -v .
  displayName: 'Get dependencies, then build'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/buyout-bot' 
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
  displayName: 'Zip Lambda'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'buyout-bot-zip'
    targetPath: '$(Build.ArtifactStagingDirectory)'
